Name=input("Enter the name")
Age=int(input("Enter the age"))
college=input("Enter The College")
Cgpa=float(input("ENter the CGPA"))
Place=input("Enter the Location")
print("My name is:",Name)
print("Age is",Age)
print("Collge Name",college)
print("CGPA:",Cgpa)
print("Location",Place)